platform :ios, '7.0'

target 'appClient' do
pod 'Google-Mobile-Ads-SDK'
# Pods for AppCenter
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

end
