// counter
const INCREASE = 'INCREASE'
const DECREASE = 'DECREASE'

// request
const REQUEST_POSTS = 'REQUEST_POSTS'
const RECEIVE_POSTS = 'RECEIVE_POSTS'
const INVALIDATE_POSTS = 'INVALIDATE_POSTS'

// userinfo
const GET_USERINFO = 'GET_USERINFO'
const UPDATE_USERINFO = 'UPDATE_USERINFO'

// global
const CHANGE_LOADING = 'CHANGE_LOADING'
const CHANGE_COVER = 'CHANGE_COVER'


export {
  INCREASE,
  DECREASE,

  REQUEST_POSTS,
  RECEIVE_POSTS,
  INVALIDATE_POSTS,

  GET_USERINFO,
  UPDATE_USERINFO,

  CHANGE_LOADING,
  CHANGE_COVER
};
